### register
POST http://localhost:5000/user-api/register
Content-Type: application/json

{
  "firstname":"sanjay",
  "lastname":"ponaganti",
  "email":"sanju@mail.com",
  "password":"Sanju@1214",
  "role":"STUDENT",
  "profileImageUrl":"",
  "isUserActive":true
}

### login
POST http://localhost:5000/user-api/login
Content-Type: application/json

{
  "email":"sanju@mail.com",
  "password":"Sanju@1214"
}



### student-> add academic-details
POST http://localhost:5000/student-api/add-academicDetails
Content-Type: application/json

{
  "rollNumber":"24eg105m58",
  "branch":"cse",
  "cgpa":8.2,
  "graduationYear":2028,
  "noBacklogs":true,
  "resume":"resume.jpg",
  "linkedIn":"linkedin.com",
  "github":"github.com"
}

###get academic details
GET http://localhost:5000/student-api/get-academicDetails


### get-jobs
GET http://localhost:5000/student-api/get-jobs


### apply for job
POST http://localhost:5000/student-api/job-application
Content-Type: application/json

{
  "studentId":"6a0c27ac325771ab6fec4170",
  "jobId":"6a0ec152fd77a6aa7de9f18f",
  "companyName":"Google",
  "jobRole":"Software Engineer",
  "CGPA":8.2,
  "eligibleBranches":"CSE",
  "driveDate":"2026-06-15",
  "applicationStatus":"APPLIED",
  "currentRound":"Application Submitted"
}

### delete/withdraw job application
DELETE http://localhost:5000/student-api/withdraw-application/6a0ecbcf53b253c0d373abe1

###register-company
POST http://localhost:5000/user-api/register
Content-Type: application/json

{
  "firstname":"sundar",
  "lastname":"pichai",
  "email":"sundar@mail.com",
  "password":"Sanju@1214",
  "role":"RECRUITER",
  "profileImageUrl":"",
  "isUserActive":true
}

### login-company
POST http://localhost:5000/user-api/login
Content-Type: application/json

{
  "email":"sundar@mail.com",
  "password":"Sanju@1214"
}

###post company details
POST http://localhost:5000/company-api/companyDetails
Content-Type: application/json

{
  "companyName": "Google",
  "companyEmail": "hr@google.com",
  "companyWebsite": "https://www.google.com",
  "companyLocation": "Hyderabad, India",
  "companyType": "Product Based",
  "companyDescription": "Google is a multinational technology company specializing in internet-related services, cloud computing, AI, and digital products.",
  "hrName": "Sundar Recruiter",
  "hrPhone": "9876543210",
  "hrLinkedIn": "https://linkedin.com/in/googlehr",
  "companyLogo": "google-logo.png"
}

###get company details
GET http://localhost:5000/company-api/get-companyDetails


### create job posting
POST http://localhost:5000/company-api/job-postings
Content-Type: application/json

{
  "job_id":"job_id_01",
  "recruiterId":"6a0d8477a6ae5b01bfe43b2e",
  "companyName":"Google",
  "jobRole":"Software Engineer",
  "package":"18 LPA",
  "location":"Hyderabad",
  "eligibleBranches":[
    "CSE",
    "IT",
    "ECE"
  ],
  "minimumCGPA":7.5,
  "driveDate":"2026-06-15",
  "lastDateToApply":"2026-06-10",
  "status":"OPEN"
}

###get-applications
GET http://localhost:5000/company-api/get-applications

### logout
GET http://localhost:5000/user-api/logout